# Generated by Django 4.1.1 on 2022-09-27 13:25

import base.models.item_models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('slug', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(default=base.models.item_models.create_id, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('youtube_url', models.CharField(default='', max_length=200)),
                ('tags', models.ManyToManyField(to='base.tag')),
            ],
        ),
    ]
