# Generated by Django 4.1.1 on 2022-10-10 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_comment_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.ForeignKey(default='SpHM8OcbE5WTyPUuvC9Bhf', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='shooting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
