# Generated by Django 4.1.1 on 2022-10-12 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_item_author_item_shooting_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-updated_at']},
        ),
    ]
