# Generated by Django 4.1.1 on 2022-10-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_item_tags_item_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='youtube_url',
            field=models.CharField(default='', max_length=11),
        ),
    ]
