# Generated by Django 4.1.1 on 2022-10-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_item_description_alter_item_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
